cmd_vel_mux_node:
  ros__parameters:
    joy_input_topic: "/cmd_vel_joy"
    remote_input_topic: "/cmd_vel_remote"
    output_topic: "/cmd_vel"
    active_source: "joy"
    source_timeout_sec: 0.5
    timeout_mode: "fallback"   # brake | fallback
    fallback_source: "remote"  # joy 超时自动切到 remote
    lock_active_source: false
